    if: github.repository == 'QW-Group/ezquake-source'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
       target: [linux-x86_64]
       include:
         - target: linux-x86_64
           platform: x86_64

    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install dependencies
      run: sudo apt-get install libfuse2

    - name: Build
      run: ./misc/appimage/appimage-manual_creation.sh

    - uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.target }}-AppImage
        path: ezQuake-${{ matrix.platform }}.AppImage
