name: test
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Build txt2c
      run: msbuild misc\vstudio\txt2c\txt2c.vcxproj -t:rebuild -property:Configuration=Release

    - name: Make dir
      run: mkdir .vs

    - name: Copy txt2c
      run: cp misc\vstudio\txt2c\.vs\txt2c.exe .vs\

    - name: Build modern client
      run: msbuild ezQuake.vcxproj -t:rebuild -property:Configuration=rls-modern x64

    - name: Archive modern client
      uses: actions/upload-artifact@v3
      with:
        name: ezQuake-glsl
        path: .vs\Win32\rls-modern\Output\ezQuake.exe
