name: test
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
       target: [windows-glsl-x64, windows-glsl-x86, windows-opengl-x64, windows-opengl-x86, windows-combined-x64, windows-combined-x86]
       include:
         - target: windows-glsl-x64
           config: rls-modern
           platform: x64
         - target: windows-glsl-x86
           config: rls-modern
           platform: Win32
         - target: windows-opengl-x64
           config: rls-classic
           platform: x64
         - target: windows-opengl-x86
           config: rls-classic
           platform: Win32
         - target: windows-combined-dbg-x64
           config: dbg-all
           platform: x64
         - target: windows-combined-dbg-x86
           config: dbg-all
           platform: Win32

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Build txt2c
      run: msbuild misc\vstudio\txt2c\txt2c.vcxproj -t:rebuild -property:Configuration=Release

    - name: Make dir
      run: mkdir .vs

    - name: Copy txt2c
      run: cp misc\vstudio\txt2c\.vs\txt2c.exe .vs\

    - name: Build ezquake
      run: msbuild ezQuake.vcxproj -t:rebuild -property:Configuration=${{ matrix.config }} -property:Platform=${{ matrix.platform }}

    - name: Archive 64bit modern client
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.target }}
        path: .vs\${{ matrix.platform }}\${{ matrix.config }}\Output\ezQuake.exe
