name: test
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Build app for release
      run: msbuild ezQuake.vcxproj -t:rebuild -property:Configuration=rls-modern
